### ISSUE TITLE
Needs Laravel 7 support

### ISSUE THREAD

**Issue by SteJaySulli** [langleyfoxall/php-simple-google-maps#8]
This package blocks installation for Laravel 7 projects:

` langleyfoxall/simple-google-maps v1.0.0 requires laravel/framework ^5.1||^6.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].`

This may be as simple as adding `^7.0` to composer.json, but I don't currently have time to test it.

**Comment by Jord-JD** [comment]
@SteJaySulli Added support in v1.1.0.
