### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by SteJaySulli** [langleyfoxall/php-simple-google-maps#9]
This package is locked to guzzle v 6.x -- Laravel 8 now uses 7.x; there are breaking changes as listed [here](https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70).

It's also worth noting that guzzle 7.x removes PHP 5 support, and more importantly sets the minimum PHP version to 7.2 -- I have seen dependent packages (laravel-addresses for one) that have the minimum set to 7.1, so upgrading could cause breaking changes for legacy software running on PHP 7.1.

I will look further into this when I get the chance, but I've raised this issue so that it doesn't get forgotten and to welcome input from you other devs.

**Comment by Jord-JD** [comment]
Provision Laravel 8 compatibility added in this release: https://github.com/langleyfoxall/php-simple-google-maps/releases/tag/v1.2.0

Requires full tested. Please update this issue if you testing in Laravel 8 goes well or has problems.

**Comment by Jord-JD** [comment]
Closing under assumption this is fine. Create a new issue if there are problems.
